
package JFrames;

import connection.DbaConnection;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class MainPlanilla extends javax.swing.JFrame {
    

    
    public MainPlanilla() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Pagina principal");
        this.setExtendedState(MainPlanilla.MAXIMIZED_BOTH);
    }

       @Override
    public Image getIconImage(){
    Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("./brackgournd/icon.png"));
    return retValue;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contenido = new javax.swing.JScrollPane();
        container = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        logo = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        btnCargarArchivo = new javax.swing.JButton();
        btnNuevaEmpresa = new javax.swing.JButton();
        btnMayorde3000 = new javax.swing.JButton();
        btnSueldoMinimo = new javax.swing.JButton();
        btnSuspendidos = new javax.swing.JButton();
        logOut = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JButton();
        main1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(800, 669));
        setSize(new java.awt.Dimension(1000, 1000));
        getContentPane().setLayout(new java.awt.CardLayout());

        contenido.setMinimumSize(new java.awt.Dimension(1097, 871));

        container.setMinimumSize(new java.awt.Dimension(1097, 871));
        container.setLayout(new java.awt.BorderLayout(0, 5));

        header.setBackground(new java.awt.Color(92, 88, 52));
        header.setAlignmentX(5.0F);
        header.setAlignmentY(6.0F);
        header.setAutoscrolls(true);
        header.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        header.setFocusTraversalPolicyProvider(true);
        header.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        header.setName(""); // NOI18N
        header.setPreferredSize(new java.awt.Dimension(852, 130));
        header.setLayout(new javax.swing.BoxLayout(header, javax.swing.BoxLayout.X_AXIS));

        logo.setBackground(new java.awt.Color(92, 91, 80));
        logo.setMaximumSize(new java.awt.Dimension(130, 100));
        logo.setMinimumSize(new java.awt.Dimension(90, 90));
        logo.setName(""); // NOI18N

        icon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brackgournd/mainIcon.jpg"))); // NOI18N
        icon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        icon.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        icon.setIconTextGap(10);
        icon.setMaximumSize(new java.awt.Dimension(100, 100));
        icon.setMinimumSize(new java.awt.Dimension(90, 90));
        icon.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        header.add(logo);

        menu.setBackground(new java.awt.Color(92, 91, 80));
        menu.setMaximumSize(new java.awt.Dimension(1700, 32767));
        menu.setPreferredSize(new java.awt.Dimension(800, 100));
        menu.setLayout(new java.awt.GridBagLayout());

        btnCargarArchivo.setBackground(new java.awt.Color(217, 217, 217));
        btnCargarArchivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCargarArchivo.setForeground(new java.awt.Color(0, 0, 0));
        btnCargarArchivo.setText("Cargar Archivo");
        btnCargarArchivo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCargarArchivo.setPreferredSize(new java.awt.Dimension(132, 40));
        btnCargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarArchivoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        menu.add(btnCargarArchivo, gridBagConstraints);

        btnNuevaEmpresa.setBackground(new java.awt.Color(217, 217, 217));
        btnNuevaEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevaEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        btnNuevaEmpresa.setText("Registro de empresa");
        btnNuevaEmpresa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevaEmpresa.setPreferredSize(new java.awt.Dimension(169, 40));
        btnNuevaEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaEmpresaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        menu.add(btnNuevaEmpresa, gridBagConstraints);

        btnMayorde3000.setBackground(new java.awt.Color(217, 217, 217));
        btnMayorde3000.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMayorde3000.setForeground(new java.awt.Color(0, 0, 0));
        btnMayorde3000.setText("Mayor de 3000");
        btnMayorde3000.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMayorde3000.setPreferredSize(new java.awt.Dimension(131, 40));
        btnMayorde3000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMayorde3000ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        menu.add(btnMayorde3000, gridBagConstraints);

        btnSueldoMinimo.setBackground(new java.awt.Color(217, 217, 217));
        btnSueldoMinimo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSueldoMinimo.setForeground(new java.awt.Color(0, 0, 0));
        btnSueldoMinimo.setText("Sueldo Minimo");
        btnSueldoMinimo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSueldoMinimo.setPreferredSize(new java.awt.Dimension(131, 40));
        btnSueldoMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSueldoMinimoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        menu.add(btnSueldoMinimo, gridBagConstraints);

        btnSuspendidos.setBackground(new java.awt.Color(217, 217, 217));
        btnSuspendidos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSuspendidos.setForeground(new java.awt.Color(0, 0, 0));
        btnSuspendidos.setText("Suspendidos");
        btnSuspendidos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSuspendidos.setPreferredSize(new java.awt.Dimension(114, 40));
        btnSuspendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuspendidosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        menu.add(btnSuspendidos, gridBagConstraints);

        header.add(menu);

        logOut.setBackground(new java.awt.Color(92, 91, 80));
        logOut.setMaximumSize(new java.awt.Dimension(150, 100));
        logOut.setMinimumSize(new java.awt.Dimension(90, 100));

        btnLogOut.setBackground(new java.awt.Color(219, 209, 125));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(0, 0, 0));
        btnLogOut.setText("LogOut");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logOutLayout = new javax.swing.GroupLayout(logOut);
        logOut.setLayout(logOutLayout);
        logOutLayout.setHorizontalGroup(
            logOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logOutLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        logOutLayout.setVerticalGroup(
            logOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logOutLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        header.add(logOut);

        container.add(header, java.awt.BorderLayout.PAGE_START);

        main1.setBackground(new java.awt.Color(219, 209, 125));
        main1.setMinimumSize(new java.awt.Dimension(1097, 871));
        main1.setPreferredSize(new java.awt.Dimension(1097, 871));
        main1.setLayout(new javax.swing.BoxLayout(main1, javax.swing.BoxLayout.LINE_AXIS));
        container.add(main1, java.awt.BorderLayout.CENTER);

        contenido.setViewportView(container);

        getContentPane().add(contenido, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaEmpresaActionPerformed
        NuevaEmpresa nuevaEmpresa;
        new NuevaEmpresa().setVisible(true);
    }//GEN-LAST:event_btnNuevaEmpresaActionPerformed

    private void btnCargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarArchivoActionPerformed
       IngresoPlanilla  ingresoPlanilla;
       new IngresoPlanilla().setVisible(true);
    }//GEN-LAST:event_btnCargarArchivoActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        Login login;
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnMayorde3000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMayorde3000ActionPerformed

      MayorDe3000 p1 = new MayorDe3000();
      showPanel(p1);
    }//GEN-LAST:event_btnMayorde3000ActionPerformed

    private void btnSueldoMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSueldoMinimoActionPerformed
    SueldoMinimo sueldoMinimo = new SueldoMinimo();
        showPanel(sueldoMinimo);
    }//GEN-LAST:event_btnSueldoMinimoActionPerformed

    private void btnSuspendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuspendidosActionPerformed
        Suspendidos suspendidos = new Suspendidos();
        showPanel(suspendidos);
    }//GEN-LAST:event_btnSuspendidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPlanilla().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarArchivo;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMayorde3000;
    private javax.swing.JButton btnNuevaEmpresa;
    private javax.swing.JButton btnSueldoMinimo;
    private javax.swing.JButton btnSuspendidos;
    private javax.swing.JPanel container;
    private javax.swing.JScrollPane contenido;
    private javax.swing.JPanel header;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel logOut;
    private javax.swing.JPanel logo;
    private javax.swing.JPanel main1;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables



        private void showPanel(JPanel p1) {
        p1.setBounds(0, 0, 0, 0);
        main1.removeAll();
        main1.add(p1, BorderLayout.CENTER);
        main1.revalidate();
        main1.repaint();
    }
        

}
